{"message":"name is required.","stack":"Error: name is required.\n    at SchemaController.validateRequiredColumns (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Controllers/SchemaController.js:1133:13)\n    at schemaPromise.then.schema (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Controllers/SchemaController.js:1285:19)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":111,"level":"error","timestamp":"2019-02-12T12:02:46.609Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at _rest.default.get.then.response (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/ClassesRouter.js:70:15)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":101,"level":"error","timestamp":"2019-02-12T12:04:48.866Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:08:44.505Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:14:15.090Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:14:30.233Z"}
{"error":{"message":"Invalid function: \"signUp\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"signUp\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"signUp\"', code: 141 }","timestamp":"2019-02-12T12:15:11.309Z"}
{"message":"Invalid function: \"signUp\"","stack":"Error: Invalid function: \"signUp\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T12:15:11.311Z"}
{"error":{"message":"Invalid function: \"signUp\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"signUp\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"signUp\"', code: 141 }","timestamp":"2019-02-12T12:20:02.494Z"}
{"message":"Invalid function: \"signUp\"","stack":"Error: Invalid function: \"signUp\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T12:20:02.496Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:20:10.091Z"}
{"error":{"message":"Invalid function: \"singup\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"singup\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"singup\"', code: 141 }","timestamp":"2019-02-12T12:38:28.066Z"}
{"message":"Invalid function: \"singup\"","stack":"Error: Invalid function: \"singup\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T12:38:28.069Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:43:04.206Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:45:59.816Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:56:36.443Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:56:53.673Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:57:03.421Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T12:58:37.241Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:02:33.479Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:03:42.083Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:05:45.862Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:07:30.410Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:10:35.496Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:10:58.088Z"}
{"error":{"message":"Invalid function: \"singup2\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"singup2\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"singup2\"', code: 141 }","timestamp":"2019-02-12T13:15:39.474Z"}
{"message":"Invalid function: \"singup2\"","stack":"Error: Invalid function: \"singup2\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T13:15:39.481Z"}
{"error":{"message":"Invalid function: \"singup2\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"singup2\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"singup2\"', code: 141 }","timestamp":"2019-02-12T13:16:14.865Z"}
{"message":"Invalid function: \"singup2\"","stack":"Error: Invalid function: \"singup2\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T13:16:14.868Z"}
{"error":{"message":"Invalid function: \"singup2\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"singup2\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"singup2\"', code: 141 }","timestamp":"2019-02-12T13:17:16.132Z"}
{"message":"Invalid function: \"singup2\"","stack":"Error: Invalid function: \"singup2\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T13:17:16.136Z"}
{"error":{"message":"Invalid function: \"singup2\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"singup2\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"singup2\"', code: 141 }","timestamp":"2019-02-12T13:17:54.181Z"}
{"message":"Invalid function: \"singup2\"","stack":"Error: Invalid function: \"singup2\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T13:17:54.183Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:19:45.392Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:45:46.492Z"}
{"error":{"message":"Invalid function: \"cep\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"cep\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"cep\"', code: 141 }","timestamp":"2019-02-12T13:46:48.643Z"}
{"message":"Invalid function: \"cep\"","stack":"Error: Invalid function: \"cep\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T13:46:48.648Z"}
{"error":{"message":"Invalid function: \"cep\"","code":141},"level":"error","message":"Error handling request: { Error: Invalid function: \"cep\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3) message: 'Invalid function: \"cep\"', code: 141 }","timestamp":"2019-02-12T13:47:52.972Z"}
{"message":"Invalid function: \"cep\"","stack":"Error: Invalid function: \"cep\"\n    at handleCloudFunction (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:134:13)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/PromiseRouter.js:175:7\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/layer.js:95:5)\n    at /home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:281:22\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:354:14)\n    at param (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/home/support/Documents/repositorios/catch-cep-api/node_modules/express/lib/router/index.js:410:3)","code":141,"level":"error","timestamp":"2019-02-12T13:47:52.974Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:48:03.595Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:51:06.626Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:53:48.169Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:55:38.584Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T13:59:44.896Z"}
{"message":"Account already exists for this username.","stack":"Error: Account already exists for this username.\n    at config.database.find.then.results (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/RestWrite.js:494:13)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":202,"level":"error","timestamp":"2019-02-12T13:59:45.233Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T14:00:11.281Z"}
{"message":"Account already exists for this username.","stack":"Error: Account already exists for this username.\n    at config.database.find.then.results (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/RestWrite.js:494:13)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":202,"level":"error","timestamp":"2019-02-12T14:00:11.668Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T14:00:41.426Z"}
{"functionName":"singup","params":{},"level":"info","message":"Ran cloud function singup for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T14:22:41.785Z"}
{"message":"Account already exists for this username.","stack":"Error: Account already exists for this username.\n    at config.database.find.then.results (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/RestWrite.js:494:13)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":202,"level":"error","timestamp":"2019-02-12T14:22:42.177Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T14:22:52.614Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T14:30:27.637Z"}
{"functionName":"cep","error":{"message":"response is not defined","code":141},"params":{},"level":"error","message":"Failed running cloud function cep for user undefined with:\n  Input: {}\n  Error: {\"message\":\"response is not defined\",\"code\":141}","timestamp":"2019-02-12T15:14:28.550Z"}
{"message":"response is not defined","stack":"Error: response is not defined\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-12T15:14:28.563Z"}
{"functionName":"cep","error":{"message":"response is not defined","code":141},"params":{},"level":"error","message":"Failed running cloud function cep for user undefined with:\n  Input: {}\n  Error: {\"message\":\"response is not defined\",\"code\":141}","timestamp":"2019-02-12T15:15:03.841Z"}
{"message":"response is not defined","stack":"Error: response is not defined\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-12T15:15:03.844Z"}
{"functionName":"create","error":{"message":"lucas.set is not a function","code":141},"params":{},"level":"error","message":"Failed running cloud function create for user undefined with:\n  Input: {}\n  Error: {\"message\":\"lucas.set is not a function\",\"code\":141}","timestamp":"2019-02-12T15:23:28.270Z"}
{"message":"lucas.set is not a function","stack":"Error: lucas.set is not a function\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-12T15:23:28.284Z"}
{"functionName":"create","error":{"message":"GameScore is not defined","code":141},"params":{},"level":"error","message":"Failed running cloud function create for user undefined with:\n  Input: {}\n  Error: {\"message\":\"GameScore is not defined\",\"code\":141}","timestamp":"2019-02-12T15:26:32.606Z"}
{"message":"GameScore is not defined","stack":"Error: GameScore is not defined\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-12T15:26:32.620Z"}
{"functionName":"create","error":{"message":"gameScore is not defined","code":141},"params":{},"level":"error","message":"Failed running cloud function create for user undefined with:\n  Input: {}\n  Error: {\"message\":\"gameScore is not defined\",\"code\":141}","timestamp":"2019-02-12T15:30:33.356Z"}
{"message":"gameScore is not defined","stack":"Error: gameScore is not defined\n    at error (/home/support/Documents/repositorios/catch-cep-api/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at <anonymous>","code":141,"level":"error","timestamp":"2019-02-12T15:30:33.369Z"}
{"functionName":"create","params":{},"level":"info","message":"Ran cloud function create for user undefined with:\n  Input: {}\n  Result: undefined","timestamp":"2019-02-12T15:31:30.365Z"}
